# Generated by Django 5.1.6 on 2025-04-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0002_remove_voyagelist_charter_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagelist',
            name='charter_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifs.chartertype'),
        ),
    ]
