# Generated by Django 5.1.6 on 2025-04-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0003_remove_voyagelist_charterer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyagelist',
            name='charterer',
        ),
    ]
