# Generated by Django 5.1.6 on 2025-04-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0004_remove_voyagelist_charterer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyagelist',
            name='charter_type',
        ),
    ]
