# Generated by Django 5.1.6 on 2025-04-24 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0006_voyagelist_chartertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyagelist',
            name='charterer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ifs.chartererlist'),
        ),
    ]
