# Generated by Django 5.1.6 on 2025-04-29 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enr', '0011_benchmarkedenrparameter'),
        ('ifs', '0007_voyagelist_charterer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagedataengine',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='VoyageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(max_length=3)),
                ('date_time', models.DateTimeField()),
                ('timezone', models.IntegerField()),
                ('activity', models.CharField(max_length=20)),
                ('step', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('loc_atfrom', models.CharField(blank=True, max_length=5, null=True)),
                ('loc_to', models.CharField(blank=True, max_length=5, null=True)),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enr.vessellist')),
                ('voyage_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifs.voyagelist')),
            ],
            options={
                'unique_together': {('vessel', 'voyage_number', 'date_time')},
            },
        ),
    ]
