# Generated by Django 5.1.6 on 2025-04-29 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0008_alter_voyagedataengine_duration_voyagereport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voyagedataengine',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='voyagedataengine',
            name='voyage_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifs.voyagereport'),
        ),
        migrations.RemoveField(
            model_name='voyagedataengine',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='voyagedataengine',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='voyagedataengine',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='voyagedataengine',
            name='loc_atfrom',
        ),
        migrations.RemoveField(
            model_name='voyagedataengine',
            name='loc_to',
        ),
        migrations.RemoveField(
            model_name='voyagedataengine',
            name='step',
        ),
        migrations.RemoveField(
            model_name='voyagedataengine',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='voyagedataengine',
            name='trip_number',
        ),
        migrations.RemoveField(
            model_name='voyagedataengine',
            name='vessel',
        ),
        migrations.RemoveField(
            model_name='voyagedataengine',
            name='voyage_number',
        ),
    ]
