# Generated by Django 5.1.6 on 2025-04-29 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0009_alter_voyagedataengine_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoyageDataDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fw_rob', models.FloatField(blank=True, null=True)),
                ('fw_supply', models.FloatField(blank=True, null=True)),
                ('fw_generated', models.FloatField(blank=True, null=True)),
                ('fw_consumption_pernoon', models.FloatField(blank=True, null=True)),
                ('fw_remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('dwt_cargo_1_rob', models.FloatField(blank=True, null=True)),
                ('dwt_cargo_1_type', models.CharField(blank=True, max_length=20, null=True)),
                ('dwt_cargo_2_rob', models.FloatField(blank=True, null=True)),
                ('dwt_cargo_2_type', models.CharField(blank=True, max_length=20, null=True)),
                ('dwt_ballast_water', models.FloatField(blank=True, null=True)),
                ('dwt_constant', models.FloatField(blank=True, null=True)),
                ('dwt_other', models.FloatField(blank=True, null=True)),
                ('dwt_total', models.FloatField(blank=True, null=True)),
                ('draft_f', models.FloatField(blank=True, null=True)),
                ('draft_m', models.FloatField(blank=True, null=True)),
                ('draft_a', models.FloatField(blank=True, null=True)),
                ('hogsag', models.FloatField(blank=True, null=True)),
                ('dist_lastport', models.FloatField(blank=True, null=True)),
                ('dist_24hours', models.FloatField(blank=True, null=True)),
                ('dist_togo', models.FloatField(blank=True, null=True)),
                ('speed_log', models.FloatField(blank=True, null=True)),
                ('speed_gps', models.FloatField(blank=True, null=True)),
                ('speed_average', models.FloatField(blank=True, null=True)),
                ('speed_slip', models.FloatField(blank=True, null=True)),
                ('coord_latdegree', models.FloatField(blank=True, null=True)),
                ('coord_latdecimal', models.FloatField(blank=True, null=True)),
                ('coord_latq', models.CharField(blank=True, max_length=5, null=True)),
                ('coord_longdegree', models.FloatField(blank=True, null=True)),
                ('coord_longdecimal', models.FloatField(blank=True, null=True)),
                ('coord_longq', models.CharField(blank=True, max_length=5, null=True)),
                ('coord_notes', models.CharField(blank=True, max_length=5, null=True)),
                ('pos_hs', models.IntegerField(blank=True, null=True)),
                ('pos_steering_rh', models.IntegerField(blank=True, null=True)),
                ('pos_barometer', models.FloatField(blank=True, null=True)),
                ('pos_temperature', models.FloatField(blank=True, null=True)),
                ('wind_dir', models.CharField(blank=True, max_length=5, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_bf_scale', models.IntegerField(blank=True, null=True)),
                ('wind_condition', models.CharField(blank=True, max_length=20, null=True)),
                ('wave_height', models.FloatField(blank=True, null=True)),
                ('wave_douglas_scale', models.IntegerField(blank=True, null=True)),
                ('wave_state', models.CharField(blank=True, max_length=20, null=True)),
                ('wave_swell', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('voyage_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifs.voyagereport')),
            ],
        ),
    ]
