# Generated by Django 5.1.6 on 2025-04-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0010_voyagedatadeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagedatadeck',
            name='coord_notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
