# Generated by Django 5.1.6 on 2025-05-02 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enr', '0011_benchmarkedenrparameter'),
        ('ifs', '0011_alter_voyagedatadeck_coord_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoyagePerformanceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('me_fo_cons_in_kl', models.FloatField()),
                ('me_do_cons_in_kl', models.FloatField()),
                ('me_rh', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enr.vessellist')),
                ('voyage_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifs.voyagelist')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
