# Generated by Django 5.1.6 on 2025-06-17 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0013_voyagesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LubOilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fueloil_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LubOilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rob', models.FloatField(blank=True, null=True)),
                ('supply', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('voyage_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifs.voyagereport')),
                ('lo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifs.luboiltype')),
            ],
            options={
                'unique_together': {('voyage_report', 'lo_type')},
            },
        ),
    ]
