# Generated by Django 5.1.6 on 2025-06-17 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0015_delete_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoyageRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.IntegerField()),
                ('port_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=20)),
                ('visited', models.BooleanField(default=False)),
                ('current', models.BooleanField(default=False)),
                ('arrival_date', models.DateTimeField()),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='ifs.voyagelist')),
            ],
        ),
    ]
