# Generated by Django 5.1.6 on 2025-06-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0016_voyageroute_delete_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
