# Generated by Django 5.1.6 on 2025-06-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0017_delete_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyageroute',
            name='trip_id',
        ),
    ]
