# Generated by Django 5.1.6 on 2025-09-16 04:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0018_remove_voyageroute_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyagereport',
            name='vesselActivityId',
            field=models.UUIDField(null=True, blank=True),  # temporarily allow null
        ),
    ]
