# Generated by Django 5.1.6 on 2025-09-16 04:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0020_populate_vesselactivityid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagereport',
            name='vesselActivityId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
