# Generated by Django 5.1.6 on 2025-09-23 04:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0021_alter_voyagereport_vesselactivityid'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyagelist',
            name='voyageUuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
