# Generated by Django 5.1.6 on 2025-09-25 03:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enr', '0011_benchmarkedenrparameter'),
        ('ifs', '0024_alter_voyagelist_voyageuuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagelist',
            name='voyageUuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='TripSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_duration', models.IntegerField()),
                ('total_fo_cons', models.FloatField()),
                ('total_do_cons', models.FloatField()),
                ('sailing_duration', models.IntegerField()),
                ('sailing_fo_cons', models.FloatField()),
                ('sailing_do_cons', models.FloatField()),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enr.vessellist')),
                ('voyage_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifs.voyagelist')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
