# Generated by Django 5.1.6 on 2025-09-25 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0025_alter_voyagelist_voyageuuid_tripsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripsummary',
            name='sailing_do_cons',
        ),
        migrations.RemoveField(
            model_name='tripsummary',
            name='sailing_duration',
        ),
        migrations.RemoveField(
            model_name='tripsummary',
            name='sailing_fo_cons',
        ),
        migrations.RemoveField(
            model_name='tripsummary',
            name='total_do_cons',
        ),
        migrations.RemoveField(
            model_name='tripsummary',
            name='total_fo_cons',
        ),
        migrations.AlterField(
            model_name='tripsummary',
            name='total_duration',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='TripFuelSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_rob', models.FloatField(blank=True, null=True)),
                ('end_rob', models.FloatField(blank=True, null=True)),
                ('supply_qty', models.FloatField(blank=True, null=True)),
                ('correction_qty', models.FloatField(blank=True, null=True)),
                ('total_cons', models.FloatField(blank=True, null=True)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifs.fueloiltype')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_summaries', to='ifs.tripsummary')),
            ],
            options={
                'unique_together': {('trip', 'fuel_type')},
            },
        ),
    ]
