# Generated by Django 5.1.6 on 2025-09-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0026_remove_tripsummary_sailing_do_cons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsummary',
            name='trip_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
