# Generated by Django 5.1.6 on 2025-09-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifs', '0027_tripsummary_trip_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripfuelsummary',
            name='total_cons',
        ),
        migrations.AddField(
            model_name='tripfuelsummary',
            name='flowmeter_cons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripfuelsummary',
            name='sounding_cons',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
