# Generated by Django 5.1.6 on 2025-03-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('movement', models.CharField(blank=True, max_length=50, null=True)),
                ('displacement', models.CharField(blank=True, max_length=50, null=True)),
                ('parameter', models.CharField(max_length=20)),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('vessel', 'date', 'parameter')},
            },
        ),
    ]
