# Generated by Django 5.1.6 on 2025-03-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enr', '0002_parameterlist_alter_enrparameter_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vesselname', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='enrparameter',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enr.vessellist'),
        ),
    ]
