# Generated by Django 5.1.6 on 2025-03-20 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enr', '0003_vessellist_alter_enrparameter_vessel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeaTrialParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('displacement', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.FloatField()),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enr.parameterlist')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enr.vessellist')),
            ],
            options={
                'unique_together': {('vessel', 'session', 'timestamp', 'parameter')},
            },
        ),
    ]
