# Generated by Django 5.1.6 on 2025-03-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enr', '0004_seatrialparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterlist',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
