# Generated by Django 5.1.6 on 2025-03-24 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enr', '0005_parameterlist_is_calculated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeaTrialSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enr.vessellist')),
            ],
        ),
        migrations.CreateModel(
            name='SeaTrialModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient_a', models.FloatField()),
                ('coefficient_b', models.FloatField(blank=True, null=True)),
                ('coefficient_c', models.FloatField(blank=True, null=True)),
                ('coefficient_determination', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameter_x', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='independent_models', to='enr.parameterlist')),
                ('parameter_y', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_models', to='enr.parameterlist')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enr.vessellist')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enr.seatrialsession')),
            ],
        ),
        migrations.AlterField(
            model_name='seatrialparameter',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enr.seatrialsession'),
        ),
    ]
