# Generated by Django 5.1.6 on 2025-03-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enr', '0006_seatrialsession_seatrialmodels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatrialmodels',
            name='formula_type',
            field=models.CharField(choices=[('quadratic', 'Quadratic (y = ax² + bx + c)')], default='quadratic', max_length=20),
        ),
        migrations.AddField(
            model_name='seatrialmodels',
            name='model_type',
            field=models.CharField(choices=[('internal', 'FOC vs M/E Power'), ('external', 'Ship Speed vs M/E Power')], default='internal', max_length=20),
        ),
    ]
