# Generated by Django 5.1.6 on 2025-03-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enr', '0007_seatrialmodels_formula_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatrialmodels',
            unique_together={('vessel', 'session', 'model_type')},
        ),
    ]
