# Generated by Django 5.1.6 on 2025-03-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enr', '0008_alter_seatrialmodels_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatrialmodels',
            name='formula_type',
            field=models.CharField(choices=[('quadratic', 'Quadratic (y = ax² + bx + c)'), ('linear', 'Linear (y = mx + b)')], default='quadratic', max_length=20),
        ),
    ]
