# Generated by Django 5.1.6 on 2025-03-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enr', '0009_alter_seatrialmodels_formula_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatrialmodels',
            name='model_type',
            field=models.CharField(choices=[('internal', 'FOC vs M/E Power'), ('external', 'Ship Speed vs M/E Power'), ('exponent', 'Power Plan vs Exponent')], default='internal', max_length=20),
        ),
    ]
