# Generated by Django 5.1.6 on 2025-03-25 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enr', '0010_alter_seatrialmodels_model_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkedEnrParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmarked_value', models.FloatField(blank=True, null=True)),
                ('difference', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enr_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enr.enrparameter')),
            ],
        ),
    ]
